'use server';
/**
 * @fileOverview This file implements "Temporal Neural Synergy" with Reverse Search Provenance.
 * 
 * - analyzeVideoForDeepfake - Performs cross-modal synchronization, temporal consistency checks, and source origin identification.
 */

import { ai } from '@/ai/genkit';
import { z } from 'genkit';

const AnalyzeVideoForDeepfakeInputSchema = z.object({
  videoDataUri: z
    .string()
    .describe("The video to analyze as a data URI."),
  learnedContext: z.string().optional().describe('MANDATORY Ground Truth context derived from historical investigations.'),
});

const AnalyzeVideoForDeepfakeOutputSchema = z.object({
  isDeepfake: z.boolean(),
  fakeCategory: z.enum(['Face Swap', 'Lip Sync', 'Full Synthetic', 'Puppet Master', 'Authentic']).describe('The specific type of video manipulation.'),
  confidence: z.number().min(0).max(100),
  explanation: z.string(),
  sourceOrigin: z.string().describe("Identified original source (e.g., '2018 Interview with BBC', 'Viral TikTok clip')."),
  originalContext: z.string().describe("Forensic evidence of original source identification."),
  neuralAncestry: z.object({
    modelFamily: z.string(),
    likelyModel: z.string(),
    fingerprintConfidence: z.number(),
  }),
  behavioralBiometrics: z.object({
    blinkConsistency: z.number().describe("Score of eye blinking naturalness (0-100)."),
    headMovementFluidity: z.number().describe("Score of head movement naturalness (0-100)."),
    temporalStability: z.number().describe("Score of frame-to-frame consistency and absence of face-shifts (0-100)."),
    notes: z.string(),
  }),
  crossModalSync: z.object({
    audioVisualAlignment: z.number(),
    lipSyncVerdict: z.string(),
    isDubbed: z.boolean(),
  }),
  suspiciousSegments: z.array(z.object({
    startTime: z.number(),
    endTime: z.number(),
    isSynthetic: z.boolean(),
    description: z.string(),
  })).optional(),
});

const temporalSynergyEngine = ai.definePrompt({
  name: 'temporalSynergyEngine',
  input: { schema: AnalyzeVideoForDeepfakeInputSchema },
  output: { schema: AnalyzeVideoForDeepfakeOutputSchema },
  prompt: `You are the Temporal Neural Forensic Analyst.

  ### NEURAL SYNERGY CONTEXT (MEMORY)
  Analyze using historical patterns and identified signatures:
  {{{learnedContext}}}

  TASK 1: CATEGORIZATION & PROVENANCE
  Categorize the manipulation:
  - Face Swap: Replacing a face on an existing body.
  - Lip Sync: Manipulating the mouth to match a new audio track.
  - Full Synthetic: Entire video is generated by AI (e.g., Sora, Veo).
  - Puppet Master: Driving a real person's movements using another's performance.

  Identify if this video is a manipulated version of an existing, real-world clip.

  TASK 2: TEMPORAL CONSISTENCY AI (CRITICAL)
  Analyze the video for frame-to-frame coherence. 
  Look specifically for sudden face shifts or "mask jumps".

  TASK 3: BEHAVIOR-BASED DETECTION
  Analyze eye blinking patterns and head movement fluidity.

  TASK 4: CROSS-MODAL SYNCHRONIZATION
  Check lip-sync vs vocal track for modal discrepancies.

  TASK 5: TIMELINE BREAKDOWN (MANDATORY)
  Identify EXACT seconds that are synthetic or real.

  Video: {{media url=videoDataUri}}`,
});

export async function analyzeVideoForDeepfake(input: z.infer<typeof AnalyzeVideoForDeepfakeInputSchema>) {
  const { output } = await temporalSynergyEngine(input);
  if (!output) throw new Error('Temporal Synergy Engine failed.');
  return output;
}
